---
- hosts: localhost
  connection: local
  tasks:
  - name: Install base packages
    become: true
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - dirmngr
      - software-properties-common
      - zsh
      - tmux
      - git
      - docker.io
      - rustc
      - cargo

  - name: Add a GPG key for SBT
    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=2EE0EA64E40A89B84B2DF73499E82A75642AC823

  - name: Add a source and GPG key for SBT
    become: true
    shell: echo "deb https://dl.bintray.com/sbt/debian /" > /etc/apt/sources.list.d/sbt.list

  - name: Install SBT package
    become: true
    apt:
      update_cache: yes
      state: latest
      name: sbt

  - name: Download Node.js installer
    get_url: url=https://deb.nodesource.com/setup_7.x dest=/tmp/nodejs_installer.sh

  - name: Execute the Node.js installer
    become: true
    script: /tmp/nodejs_installer.sh

  - name: Install Nodejs package
    become: true
    apt:
      update_cache: yes
      state: latest
      name: nodejs

  - name: Download Yarn GPG key
    get_url: url=https://dl.yarnpkg.com/debian/pubkey.gpg dest=/tmp/yarn_pubkey.gpg

  - name: Add apt key for Yarn
    become: true
    shell: apt-key add /tmp/yarn_pubkey.gpg

  - name: Add repository for Yarn
    become: true
    shell: echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

  - name: Install Yarn package
    become: true
    apt:
      update_cache: yes
      state: latest
      name: yarn

  - name: Add NeoVim repository
    apt_repository:
      repo: 'ppa:neovim-ppa/stable'

  - name: Install NeoVim
    become: true
    apt:
      name: neovim
      update_cache: yes
      state: latest

  - name: Install NeoVim-dev packages
    become: true
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - python-dev
      - python-pip
      - python3-dev
      - python3-pip

  - name: Install ruby and rails-dev packages
    become: true
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - ruby
      - build-essential
      - libpq-dev
      - ruby-dev
      - zlib1g-dev
      - pkg-config
      - libmagickwand-dev
      - imagemagick
      - libsqlite3-dev