#!/usr/bin/env zsh
#
# The dotfile manager (dmgr)
#
# Help build and manage your best *nix environment :)
#
# @rev    0.10.1
# @update 2014-11-18
# @author TADOKORO Saneyuki <saneyan@mail.gfunction.com>
#

. ~/.dmgr/src/env.zsh
. ~/.dmgr/src/util.zsh

[[ "${0}" =~ "dmgr.debug$" ]] && export DMGR_DEBUGMODE=true

_d "dmgr v${DMGR_VERSION} on DEBUG MODE"
_d '$0 (dmgr path): '$0
_d '$1 (dmgr command): '$1
_d '$2.. (options): '${@:2}
_d '$DMGR_DIST: '$DMGR_DIST
_d '$DMGR_CONFDIR: '$DMGR_CONFDIR
_d '$DMGR_FEATUREDIR: '$DMGR_FEATUREDIR
_d '$DMGR_PLUGINIDR: '$DMGR_PLUGINDIR
_d '$DMGR_HOOKDIR: '$DMGR_HOOKDIR
_d '$DMGR_INUSE: '$DMGR_INUSE
_d '$DMGR_SUPPORT: '$DMGR_SUPPORT
_d '$DMGR_PLUGIN: '$DMGR_PLUGIN
_d '$DMGR_OFFICIAL: '$DMGR_OFFICIAL
_d 'Inuse features: ' $(cat $DMGR_INUSE)
_d 'Support features: ' $(cat $DMGR_SUPPORT)
_d 'Installed plugins: ' $(cat $DMGR_PLUGIN)
_d 'Official plugins: ' $(cat $DMGR_OFFICIAL)

case $1 in
  "has")        _enforce_arg_chk $# '=' 1 && $DMGR_SRCDIR/dmgr-has $2 ;;
  "deals")      _enforce_arg_chk $# '=' 1 && $DMGR_SRCDIR/dmgr-deals $2 ;;
  "installed")  _enforce_arg_chk $# '=' 1 && $DMGR_SRCDIR/dmgr-installed $2 ;;
  "support")    _enforce_arg_chk $# '=' 1 && $DMGR_SRCDIR/dmgr-support $2 ;;
  "unsupport")  _enforce_arg_chk $# '=' 1 && $DMGR_SRCDIR/dmgr-unsupport $2 ;;
  "env")        _enforce_arg_chk $# '>=' 1 && $DMGR_SRCDIR/dmgr-env $2 ;;
  "enable")     _enforce_arg_chk $# '>=' 1 && $DMGR_SRCDIR/dmgr-enable ${@:2} ;;
  "disable")    _enforce_arg_chk $# '>=' 1 && $DMGR_SRCDIR/dmgr-disable ${@:2} ;;
  "install")    _enforce_arg_chk $# '>=' 1 && $DMGR_SRCDIR/dmgr-install ${@:2};;
  "uninstall")  _enforce_arg_chk $# '>=' 1 && $DMGR_SRCDIR/dmgr-uninstall ${@:2} ;;
  "update")     $DMGR_SRCDIR/dmgr-update ${@:2} ;;
  "edit")       $DMGR_SRCDIR/dmgr-edit $2 ;;
  "list")       $DMGR_SRCDIR/dmgr-list ;;
  "help")       $DMGR_SRCDIR/dmgr-help ;;
esac

echo "Type 'dmgr help' for more help."
exit 1
