declare -x MODE=''
declare -rx DMGR_VERSION="0.10.0"
declare -rx DMGR_DIST=$(uname -r)
declare -rx DMGR_CONFDIR=$HOME/.dmgr/conf
declare -rx DMGR_PLUGINDIR=$HOME/.dmgr/plugins
declare -rx DMGR_HOOKDIR=$HOME/.dmgr/hooks
declare -rx DMGR_PATHDIR=$HOME/.dmgr/paths
declare -rx DMGR_SRCDIR=$HOME/.dmgr/src
declare -rx DMGR_REPODIR=$(cat $DMGR_PATHDIR/_repo)
declare -rx DMGR_INUSE=$DMGR_CONFDIR/inuse.list
declare -rx DMGR_SUPPORT=$DMGR_CONFDIR/support.list
declare -rx DMGR_PLUGIN=$DMGR_CONFDIR/plugin.list
declare -rx DMGR_OFFICIAL=$DMGR_CONFDIR/official.list
export PATH=$PATH:$DMGR_SRCDIR/traps
