export XMODIFIERS="@im=ibus"
export GTK_IM_MODULE="ibus"
export QT_IM_MODULE="xim"

# Start ibus daemon which supports xterm
ibus-daemon --daemonize --xim

# Normal cursor
xsetroot -cursor_name left_ptr

# Apply X settings
xcompmgr -c &
xautolock -time 10 -locker slimlock &
unclutter -idle 1s &

[ -e ~/Pictures/bg.png ] && feh --bg-scale ~/Pictures/bg.png
[ -e ~/.xorg.d/Xdefaults ] && xrdb -load ~/.xorg.d/Xdefaults
[ -e ~/.xorg.d/xrandrrc ] && source ~/.xorg.d/xrandrrc

exec xmonad
