#!/bin/sh
export XKBOPTIONS="ctrl:nocaps"
export XMODIFIERS="@im=ibus"
export GTK_IM_MODULE="xim"
export QT_IM_MODULE="xim"

xorg_home="${HOME}/.xorg.d"
xorg_ext="xorg.d"
dmgr_ext="${HOME}/.dmgr/ext"

# I'll soon support the follwing statement
# local resources=$(dmgr --ext-files xorg.d/Xdefaults,xorg.d/Xresources)
# local sources=$(dmgr --ext-files xorg.d/xrandrrc)
xorg_resources=(\
  "${xorg_home}/Xdefaults"\
  "${xorg_home}/Xresources"\
  $(find $dmgr_ext | grep -E "${xorg_ext}/Xdefaults$" 2>/dev/null)\
  $(find $dmgr_ext | grep -E "${xorg_ext}/Xresources$" 2>/dev/null))

xorg_keyconfigs=(\
  "${xorg_home}/Xmodmap"\
  $(find $dmgr_ext | grep -E "${xorg_ext}/Xmodmap$" 2>/dev/null))

xorg_sources=(\
  "${xorg_home}/Xrandrrc"\
  "${xorg_home}/Xconfig"\
  $(find $dmgr_ext | grep -E "${xorg_ext}/Xrandrrc$" 2>/dev/null)\
  $(find $dmgr_ext | grep -E "${xorg_ext}/Xconfig$" 2>/dev/null))

xorg_inits=(\
  "${xorg_home}/Xexec"\
  $(find $dmgr_ext | grep -E "${xorg_ext}/Xexec$" 2>/dev/null))

# Apply resource settings of X Window System
for f in ${xorg_resources[@]}; do [ -e $f ] && xrdb -load $f; done

# Load keymap settings of X Window System
for f in ${xorg_keyconfigs[@]}; do [ -e $f ] && xmodmap $f; done

# Load external shell scripts
for f in ${xorg_sources[@]} ${xorg_inits[@]}; do [ -e $f ] && source $f; done

xorg_begin_session
