"
" .nvimrc - Neovim configuration file
"
" @rev    G-0.6.0
" @update 2014-09-02
" @author TADOKORO Saneyuki <saneyan@mail.gfunction.com>

if has("neovim")
  let s:python_host_init = 'python -c "import neovim; neovim.start_host()"'
  let &initpython = s:python_host_init
endif

source $HOME/.vimrc
