"
" .vimrc - Vim configuration file
"
" @rev    G-0.6.0
" @update 2014-7-9
" @author Saneyuki Tadokoro <saneyan@mail.gfunction.com>
"
" Key bindings (Leader key is commma):
" [Normal mode]
"   Leader » t » n  Switch next tab
"   Leader » t » p  Switch previous tab
"   Leader » t » e  Open a new tab
"   Leader » t » c  Close a tab
"   Leader » w » v  Split window vertically
"   Leader » w » h  Split window horizontally
"   Leader » w » q  Quit current window
"   Leader » w » t  Toggle tab type
"   Leader » c      Toggle cursor highlighting
"   Leader » d      Toggle NERDTRee
"   Leader » n      Launch NERDTree
"   Leader » m      Launch OverCommandLine
"   Leader » o      Save
"
" [Insert mode]
"

" Local functions
source $HOME/.vim/vimrc.functions

" General settings
source $HOME/.vim/vimrc.general

" Key mapping
source $HOME/.vim/vimrc.mapping

" Tab type
source $HOME/.vim/vimrc.tab-type

" Cursor settings
source $HOME/.vim/vimrc.color

" NERDTree settings
source $HOME/.vim/vimrc.nerdtree

" vim-indent-guides
source $HOME/.vim/vimrc.vim-indent-guides

" NeoComplcache settings
source $HOME/.vim/vimrc.neocomplcache

" NeoBundle settings
source $HOME/.vim/vimrc.neobundle

"" Let vim identify depending on a file type
filetype plugin indent on

"" Installation check
NeoBundleCheck

" Load local settings
if filereadable('local_setting.vim')
  source local_setting.vim
endif

