"
" .vimrc - Vim configuration file
"
" @rev    G-0.6.0
" @update 2014-7-9
" @author Saneyuki Tadokoro <saneyan@gfunction.com>
"
" Key bindings (Leader key is commma):
" [Normal mode]
"   Leader » t » n  Switch next tab
"   Leader » t » p  Switch previous tab
"   Leader » t » e  Open a new tab
"   Leader » t » c  Close a tab
"   Leader » w » v  Split window vertically
"   Leader » w » h  Split window horizontally
"   Leader » w » q  Quit current window
"   Leader » w » t  Toggle tab type
"   Leader » c      Toggle cursor highlighting
"   Leader » d      Toggle NERDTRee
"   Leader » n      Launch NERDTree
"   Leader » m      Launch OverCommandLine
"   Leader » o      Save
"
" [Insert mode]
"

" for neovim and legacy vim

" Local functions
source $HOME/.vim/functions.vim

" General settings
source $HOME/.vim/general.vim

" Key mapping
source $HOME/.vim/mapping.vim

" Tab type
source $HOME/.vim/tab-type.vim

" Cursor settings
source $HOME/.vim/color.vim

" Dein settings
source $HOME/.vim/dein.vim

"" Let vim identify depending on a file type
filetype plugin indent on

" NERDTree settings
source $HOME/.vim/nerdtree.vim

" vim-indent-guides
source $HOME/.vim/vim-indent-guides.vim

"for neovim
if has('nvim')

  " Deoplete settings
  source $HOME/.vim/deoplete.vim

" for legacy vim
else

  " NeoComplcache settings
  source $HOME/.vim/neocomplcache.vim
endif

" Load local settings
if filereadable('local_setting.vim')
  source local_setting.vim
endif
